# Numpy

### Numpy Arrays

In [1]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
type(b)

[1 2 3]


numpy.ndarray

In [2]:
a = [1, 2, 3, '5', 'a', 4.5 ]
b = np.array(a)
print(b)
# All the elements are lists

['1' '2' '3' '5' 'a' '4.5']


In [3]:
a = [1, 2, 3, '5', 4.5 ]
b = np.array(a, dtype = 'int')
print(b)


[1 2 3 5 4]


In [4]:
# Repeating the list 2 times
a = [1, 2, 3, '5', 4.5 ]
b = np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [5]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [6]:
b = np.zeros(3, dtype=int)
b
# By default they are 0

array([0, 0, 0])

In [7]:
# Creating 2D arrays
b = np.ones((2,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
b = np.zeros((3,4), dtype= int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
# If we want to fill the array with a particular number - first argument passed is size and the next is the thing we want to fill the ndarray with 
b = np.full(3, 5)
b

array([5, 5, 5])

In [10]:
# np.arange - we can get evenly spaced value within a given interval
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# np.linespace - same as arange but we have to specify the no of samples to generate.
b = np.linspace(2,10)
print(b)
# To see the step values is same throught
print(b[1] - b[0])
print(b[3] -b[2] )

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [13]:
b = np.linspace(2,10,5, dtype= int)
b
# Both the start and the stop is inclusive

array([ 2,  4,  6,  8, 10])

In [14]:
b = np.linspace(2,10,5, dtype= int, endpoint=False)
b
# stop is not inclusive

array([2, 3, 5, 6, 8])

In [15]:
# To generate an in=dentity matrix
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#using np.eye we can get un-symettric also so we can pass n*m
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Randomly generated value between 0 and 1
b = np.random.rand(3)
b

array([0.84132696, 0.40493988, 0.40806566])

In [18]:
b = np.random.rand(2,3)
b

array([[0.99481369, 0.89454772, 0.8312894 ],
       [0.03119888, 0.84194132, 0.16476484]])

In [19]:
# If we want to increase the range from 0 to 10
b = np.random.rand(3)*10
b

array([5.61830202, 1.85478791, 7.37431898])

In [20]:
# arguments as low, high, size
b = np.random.randint(0,10,3)
b

array([2, 3, 1])

In [21]:
np.random.randint(2, size=10)

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1])

In [22]:
np.random.randint(5, size=(2, 4))

array([[3, 3, 4, 2],
       [3, 3, 3, 3]])

In [23]:
# numpy.empty(shape, dtype=float, order='C', *, like=None) - Return a new array of given shape and type, without initializing entries.
np.empty(4, dtype=int)

array([       1,      256,    65536, 16777216])

### Indexing

In [24]:
# 1D Array
li = [1,2,3,4,5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [25]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides) # one element is taking 8 bypes in case of 1D array

(5,)
int32
(4,)


In [26]:
print(li[3])
print(arr[3])

4
4


In [27]:
li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides) # no of bytes to get to the next row, to get to the next element in the same row

(4, 4)
int32
(16, 4)


In [29]:
print(li_2d[2][1])
print(arr_2d[2][1])
# Another way of writing
print(arr_2d[2,1])

10
10
10


### Slicing

In [30]:
# if we want 5 6 7 from the 2d array (1st row)
print(li_2d[1][0:3])
print(arr_2d[1,0:3])

[5, 6, 7]
[5 6 7]


In [31]:
# This is not what we would expect
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [32]:
# Explanation
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [33]:
# If we want to take out 4 8 12 column wise
# In case of numpy array it works differently
print(arr_2d[0:3, 3])
# In case of normal 2D list we cannot get results column wise - we have to write a program which will include for loops to iterate over the loops

[ 4  8 12]


In [34]:
# If we want a chunk say 10,11 from row 2 and 14,15 from row 3
print(arr_2d[2:4, 1:3])
# We cannot get this ans using 2d list

[[10 11]
 [14 15]]


### Mathematical Operations

In [35]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 7  4 17 12 19]
[17 19  4 18  5]


In [36]:
# To add 1 to every element of the list
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [37]:
# In case of numpy array we can simply write it this way - numpy uses vectorisation
a = a + 1
a

array([ 8,  5, 18, 13, 20])

In [39]:
# Element wise addition
c = a +b
c

array([25, 24, 22, 31, 25])

In [40]:
g = a // b
g

array([0, 0, 4, 0, 4], dtype=int32)

In [41]:
print(a)
print(a.min())
print(a.mean())
print(a.sum())
print(a.argmin()) # index for minimum value

[ 8  5 18 13 20]
5
12.8
64
1


In [42]:
print(a)
print(b)
a > b

[ 8  5 18 13 20]
[17 19  4 18  5]


array([False, False,  True, False,  True])

In [43]:
# Similarly and, not etc
print(np.logical_or(a,b))

[ True  True  True  True  True]


### Boolean Indexing 1D

In [2]:
import numpy as np
a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 3 18 13 17  9  5 19  2]


In [3]:
# To Check if the element is grater than 10 or not
print(b>10)

[False  True  True  True False False  True False]


#### Very Important - Conditions in ndarrays

In [4]:
bool_arr = b > 10
print(bool_arr)
# We are only getting only thos elements for thos the value is true.
new_arr = b[bool_arr]
print(new_arr)

[False  True  True  True False False  True False]
[18 13 17 19]


In [5]:
# To Check if the element is grater than 10 or not and put it in one line
new_arr = b[b>10]
new_arr

array([18, 13, 17, 19])

In [6]:
new_arr = b[(b>10) & (b < 18)]
new_arr  

array([13, 17])

In [9]:
print(b)

[ 3 18 13 17  9  5 19  2]


In [11]:
c = b
c

array([ 3, 18, 13, 17,  9,  5, 19,  2])

In [12]:
# Updating Multiple Elements in one go.
c[:3] = 19
c

array([19, 19, 19, 17,  9,  5, 19,  2])

In [14]:
c[:3] = 19
print(c)
c[c>15] = 100
c

[ 19  19  19 100   9   5 100   2]


array([100, 100, 100, 100,   9,   5, 100,   2])

In [16]:
print(b)

[100 100 100 100   9   5 100   2]


In [17]:
print(b[b==100])

[100 100 100 100 100]


In [18]:
# If we want to know the indexes
ind = np.where(b == 100)
ind

(array([0, 1, 2, 3, 6], dtype=int64),)

In [19]:
# if b has 100 then print a[i]
print(a[ind])

['t' 'b' 'r' 'd' 'z']


### Boolean 2D

In [1]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[26  4  2 25 28 29]
 [25  6  7 11 16 13]
 [16 22  2 26  5 15]
 [ 6  5  2  8 28 13]
 [ 4 24 19 26  6  7]]


In [3]:
# To get the elemets greater than 20
bool_arr = a > 20
print(bool_arr)

[[ True False False  True  True  True]
 [ True False False False False False]
 [False  True False  True False False]
 [False False False False  True False]
 [False  True False  True False False]]


In [5]:
# Will give all the elements which are greater than 20
ans = a[bool_arr]
ans

array([26, 25, 28, 29, 25, 22, 26, 28, 24, 26])

In [6]:
# Updating the values of an array if it is greater thann 100
b = a
b

array([[26,  4,  2, 25, 28, 29],
       [25,  6,  7, 11, 16, 13],
       [16, 22,  2, 26,  5, 15],
       [ 6,  5,  2,  8, 28, 13],
       [ 4, 24, 19, 26,  6,  7]])

In [8]:
# bool_array works as an index -  The size of the arrays should be same
b[bool_arr] = 100
b

array([[100,   4,   2, 100, 100, 100],
       [100,   6,   7,  11,  16,  13],
       [ 16, 100,   2, 100,   5,  15],
       [  6,   5,   2,   8, 100,  13],
       [  4, 100,  19, 100,   6,   7]])

In [9]:
print(b)

[[100   4   2 100 100 100]
 [100   6   7  11  16  13]
 [ 16 100   2 100   5  15]
 [  6   5   2   8 100  13]
 [  4 100  19 100   6   7]]


In [10]:
# If we want to deal with a particular row or col of b. Here in the 3rd col all the values  which are = 100 whill show true
bool_arr = b[:, 3] == 100
print(bool_arr)

[ True False  True False  True]


In [11]:
# Updatingt he b array - bool_arr gives the rows which are to be updated, we have to specify which col we have to update the values in
b[bool_arr,3] = 99
b

array([[100,   4,   2,  99, 100, 100],
       [100,   6,   7,  11,  16,  13],
       [ 16, 100,   2,  99,   5,  15],
       [  6,   5,   2,   8, 100,  13],
       [  4, 100,  19,  99,   6,   7]])

### Numpy Broadcasting

How mumpy will treat the unequal size of array
if dimenttions are equal or one of these dimentions is 1 - then they are compatible

In [12]:
import numpy as np
x = np.random.randint (1, 10, (3,3))
y = np.random.randint (1, 10, (3,3))
print(x)
print(y)

[[9 7 8]
 [5 5 5]
 [1 8 4]]
[[4 9 5]
 [9 7 1]
 [9 5 1]]


In [13]:
ans = x - y
ans

array([[ 5, -2,  3],
       [-4, -2,  4],
       [-8,  3,  3]])

In [15]:
x = np.random.randint (1, 10, (3,3))
y = np.random.randint (1, 10, 3)
print(x)
print(y)

[[7 4 7]
 [6 6 1]
 [4 9 5]]
[9 6 4]


In [16]:
ans = x - y
print(ans)

[[-2 -2  3]
 [-3  0 -3]
 [-5  3  1]]


In [19]:
x = np.random.randint (1, 10, (3,2))
y = np.random.randint (1, 10, (2,3))
print(x)
print(y)

[[1 6]
 [5 8]
 [4 9]]
[[5 9 8]
 [1 1 3]]


In [20]:
# When the shapes are not compitable
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [21]:
# we can make them compatible by transposing one of the arrays(matrix)
t = np.transpose(y)
print(t)

[[5 1]
 [9 1]
 [8 3]]


In [23]:
# Now using that we are able to do the mathematical operation
ans = x - t
print(ans)

[[-4  5]
 [-4  7]
 [-4  6]]


In [24]:
# Resize  - numpy.resize(a, new_shape)
a=np.array([[0,1],[2,3]])
a

array([[0, 1],
       [2, 3]])

When the total size of the array does not change reshape should be used. 
In most other cases either indexing (to reduce the size) or padding (to increase the size) may be a more appropriate solution.

In [25]:
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [26]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [29]:
# Reshape - numpy.reshape(a, newshape, order='C')
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [30]:
b = np.arange(6).reshape((3, 2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

### Practical Examples

In [57]:
# Create a new column wiht killed + wounded
import numpy as np
import csv
file_obj = open('year2017.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
# These value will be stirng
np_killed = np.array(killed)
np_wounded = np.array(wounded)

# Creating a bool array and updating its values
np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'

# We cannot directry apply int as str cannot be converted to int directly
np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

killed_wounded = np_killed + np_wounded
print(killed_wounded)

# If we want to find the killed_wounded in a country
np_country = np.array(country)
bool_arr = np_country == 'India'
ans = killed_wounded[bool_arr]
print("Total no of people killed plus wounded ", np.sum(killed_wounded))
print("Total no of people killed plus wounded in India ", np.sum(ans))

[0. 2. 7. ... 0. 0. 0.]
Total no of people killed plus wounded  51372.0
Total no of people killed plus wounded in India  1167.0
