In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,"avi", 5+8j])

array(['1', '2', '3', '4', 'avi', '(5+8j)'], dtype='<U64')

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([[1,2,3],[4,5,6],[7,8]])

C:\Users\dell\AppData\Local\Temp/ipykernel_8812/1081622403.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[4,5,6],[7,8]])


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [6]:
# 2D array
np.array([[[1,2],[3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### NDIM

In [7]:
# Using ndim to make 3d array
np.array([1,2,3,4], ndmin = 3)

array([[[1, 2, 3, 4]]])

### Bitwise Difference

In [8]:
# There are i2, i4 & i8 from 16, 32 and 64 bits
arr  = np.array([(1,2), (3,4)], dtype = [("a", '<i2'), ("b", '<i8')])
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
# Represents a
type(arr[0][0])

numpy.int16

In [10]:
# Represents b
type(arr[0][1])

numpy.int64

In [11]:
arr = [[1,2], [3,4]]
arr

[[1, 2], [3, 4]]

In [12]:
print(arr[0])
print(arr[0][0])
print(arr[1][1])

[1, 2]
1
4


In [13]:
# We can use mat or matrix
mat = np.mat(arr)
mat

matrix([[1, 2],
        [3, 4]])

In [14]:
a = [1,2,32,43]

In [15]:
np.array(a)

array([ 1,  2, 32, 43])

In [16]:
# Does not convert into a array as matrix is already a type of array (list is not a type of array)
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [17]:
# Converts into array 
np.asarray(mat)

array([[1, 2],
       [3, 4]])

### Shallow and Deep Copy

In [18]:
arr

[[1, 2], [3, 4]]

In [19]:
# Shallow Copy -  any changes made will be reflected
a = arr

In [20]:
# Deep Copy - Any changes made will not be affected as data does not point to a rater a new location is created
b = np.copy(arr)

In [21]:
# The values are changed
arr[0][0] = 67
arr

[[67, 2], [3, 4]]

In [22]:
# b is the old value of arr - arrays are mutable 
b

array([[1, 2],
       [3, 4]])

In [23]:
print(arr)
arr[-1]

[[67, 2], [3, 4]]


[3, 4]

In [24]:
for i in arr:
    print(i)

[67, 2]
[3, 4]


In [25]:
np.fromfunction(lambda i,j: i ==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [26]:
np.fromfunction(lambda i,j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

### Fromiter

In [27]:
# Generator Function
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x0000021C2B8BF040>

In [28]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [29]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [30]:
np.fromstring('1,2,3,4,5', sep = ',', dtype=int)

array([1, 2, 3, 4, 5])

In [31]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]])
arr

[[67, 2], [3, 4]]

In [32]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

2
(3, 4)
12
int32


In [33]:
arr2 = np.array([ [ [1,2,3,4],[1,2,3,4] ], [ [1,2,3,4],[1,2,3,4]] ])
arr2

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [34]:
print(arr2.ndim)
print(arr2.shape) # We have 2 numbers of 2*4 data
print(arr2.size)
print(arr2.dtype)

3
(2, 2, 4)
16
int32


### Arange

In [35]:
# Similar to range function but accepts floting points as well. It accepts upper bound in case of a floting point number(it is not actually giving but it looks like it does)
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

### Linspace

In [36]:
# In between a line it will generate a data and that line will be equally divided into the number of parts we will mentoin. By default it will be 50
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [37]:
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [38]:
np.linspace(2,3,4, endpoint=False)

array([2.  , 2.25, 2.5 , 2.75])

In [39]:
np.linspace([1,2],4,axis=0)

array([[1.        , 2.        ],
       [1.06122449, 2.04081633],
       [1.12244898, 2.08163265],
       [1.18367347, 2.12244898],
       [1.24489796, 2.16326531],
       [1.30612245, 2.20408163],
       [1.36734694, 2.24489796],
       [1.42857143, 2.28571429],
       [1.48979592, 2.32653061],
       [1.55102041, 2.36734694],
       [1.6122449 , 2.40816327],
       [1.67346939, 2.44897959],
       [1.73469388, 2.48979592],
       [1.79591837, 2.53061224],
       [1.85714286, 2.57142857],
       [1.91836735, 2.6122449 ],
       [1.97959184, 2.65306122],
       [2.04081633, 2.69387755],
       [2.10204082, 2.73469388],
       [2.16326531, 2.7755102 ],
       [2.2244898 , 2.81632653],
       [2.28571429, 2.85714286],
       [2.34693878, 2.89795918],
       [2.40816327, 2.93877551],
       [2.46938776, 2.97959184],
       [2.53061224, 3.02040816],
       [2.59183673, 3.06122449],
       [2.65306122, 3.10204082],
       [2.71428571, 3.14285714],
       [2.7755102 , 3.18367347],
       [2.

In [40]:
# logspace, same as linspace but in log terms
np.logspace([2,3],5,5, axis=1, dtype=int)

array([[   100,    562,   3162,  17782, 100000],
       [  1000,   3162,  10000,  31622, 100000]])

In [41]:
np.zeros((2,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [42]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [43]:
np.ones((2,2,3,2))+4

array([[[[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.],
         [5., 5.]]],


       [[[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.],
         [5., 5.]]]])

In [44]:
d = np.linspace(4,7,40,dtype=int)
d

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7])

In [45]:
print(d.ndim)
print(d.shape)

1
(40,)


In [46]:
d.reshape(2,1,20)

array([[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7]]])

In [47]:
d.reshape(1,2,20)

array([[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7]]])

In [48]:
d.reshape(1,4,10)

array([[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 7]]])

In [49]:
# [0,1)
np.random.rand(3)

array([0.95924254, 0.04377622, 0.50769198])

In [50]:

np.random.randn(5)

array([ 0.46782064, -1.80227592,  0.10512319,  2.33215675,  0.23285941])

In [51]:
# between 5 to 60 random no is generated
np.random.randint(5,60, (4,4))

array([[10, 20, 25, 40],
       [13, 13, 15, 58],
       [16, 51, 17, 28],
       [16,  6, 52,  5]])

In [52]:
arr = np.random.randint(3,9,(3,3))
arr

array([[6, 4, 4],
       [6, 3, 3],
       [5, 8, 5]])

In [53]:
arr.reshape(1,9)

array([[6, 4, 4, 6, 3, 3, 5, 8, 5]])

In [54]:
arr.reshape(1,9)

array([[6, 4, 4, 6, 3, 3, 5, 8, 5]])

In [55]:
arr.max()

8

In [56]:
arr = np.random.randint(5,100,(5,5))
arr

array([[98, 53,  5, 24, 70],
       [14, 47, 85, 55, 66],
       [24, 67, 93, 48, 11],
       [18, 98, 21, 47,  8],
       [87, 97, 35, 24, 72]])

In [57]:
arr[3:,3:]

array([[47,  8],
       [24, 72]])

In [59]:
arr[:, [1,3]]

array([[53, 24],
       [47, 55],
       [67, 48],
       [98, 47],
       [97, 24]])

In [60]:
arr

array([[98, 53,  5, 24, 70],
       [14, 47, 85, 55, 66],
       [24, 67, 93, 48, 11],
       [18, 98, 21, 47,  8],
       [87, 97, 35, 24, 72]])

In [61]:
arr>10

array([[ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [62]:
arr[arr>10]

array([98, 53, 24, 70, 14, 47, 85, 55, 66, 24, 67, 93, 48, 11, 18, 98, 21,
       47, 87, 97, 35, 24, 72])

### Operations in Matrix

In [64]:
arr1 = np.random.randint(2,4,(3,3))
arr2 = np.random.randint(3,5,(3,3))
print(arr1)
print()
print(arr2)

[[3 3 2]
 [3 3 2]
 [3 3 2]]

[[4 3 3]
 [3 3 3]
 [4 3 4]]


In [65]:
arr1*arr2

array([[12,  9,  6],
       [ 9,  9,  6],
       [12,  9,  8]])

In [66]:
# Col of first matrix should always be equal to row dimention of the second matrix, then only multiplication is possible. 
# The dimentoin of the resultant matri will be row of first matrix  and the col of second matrix
arr1@arr2

array([[29, 24, 26],
       [29, 24, 26],
       [29, 24, 26]])

In [67]:
arr1**2

array([[9, 9, 4],
       [9, 9, 4],
       [9, 9, 4]], dtype=int32)

In [71]:
arr = np.zeros((3,4))
print(arr, '\n')
a = np.array([1,2,3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[1 2 3 4]


In [72]:
# Row wise broadcasting
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [73]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [77]:
b = np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [78]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [79]:
# Column wise brodcasting
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
# Similarly
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [89]:
arr = np.random.randint(2,5,(4,5))
arr

array([[3, 4, 2, 4, 3],
       [4, 3, 3, 4, 3],
       [3, 3, 3, 3, 2],
       [4, 2, 4, 2, 3]])

In [90]:
np.sqrt(arr)

array([[1.73205081, 2.        , 1.41421356, 2.        , 1.73205081],
       [2.        , 1.73205081, 1.73205081, 2.        , 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081, 1.41421356],
       [2.        , 1.41421356, 2.        , 1.41421356, 1.73205081]])

In [91]:
np.exp(arr)

array([[20.08553692, 54.59815003,  7.3890561 , 54.59815003, 20.08553692],
       [54.59815003, 20.08553692, 20.08553692, 54.59815003, 20.08553692],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [54.59815003,  7.3890561 , 54.59815003,  7.3890561 , 20.08553692]])

In [92]:
np.log10(arr)

array([[0.47712125, 0.60205999, 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.47712125, 0.47712125, 0.60205999, 0.47712125],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.60205999, 0.30103   , 0.60205999, 0.30103   , 0.47712125]])

In [100]:
# To generate random data that can be same for different people - The data will not change no matter how many times we execute but will still be random
np.random.seed(13)
np.random.randint(2,5,(2,3))

array([[4, 2, 4],
       [2, 4, 4]])