In [2]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
type(b)

[1 2 3]


numpy.ndarray

In [3]:
a = [1, 2, 3, '5', 'a', 4.5 ]
b = np.array(a)
print(b)
# All the elements are lists

['1' '2' '3' '5' 'a' '4.5']


In [4]:
a = [1, 2, 3, '5', 4.5 ]
b = np.array(a, dtype = 'int')
print(b)


[1 2 3 5 4]


In [5]:
# Repeating the list 2 times
a = [1, 2, 3, '5', 4.5 ]
b = np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [8]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [10]:
b = np.zeros(3, dtype=int)
b
# By default they are 0

array([0, 0, 0])

In [11]:
# Creating 2D arrays
b = np.ones((2,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
b = np.zeros((3,4), dtype= int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
# If we want to fill the array with a particular number - first argument passed is size and the next is the thing we want to fill the ndarray with 
b = np.full(3, 5)
b

array([5, 5, 5])

In [16]:
# np.arange - we can get evenly spaced value within a given interval
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# np.linespace - same as arange but we have to specify the no of samples to generate.
b = np.linspace(2,10)
print(b)
# To see the step values is same throught
print(b[1] - b[0])
print(b[3] -b[2] )

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [26]:
b = np.linspace(2,10,5, dtype= int)
b
# Both the start and the stop is inclusive

array([ 2,  4,  6,  8, 10])

In [27]:
b = np.linspace(2,10,5, dtype= int, endpoint=False)
b
# stop is not inclusive

array([2, 3, 5, 6, 8])

In [28]:
# To generate an in=dentity matrix
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#using np.eye we can get un-symettric also so we can pass n*m
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# Randomly generated value between 0 and 1
b = np.random.rand(3)
b

array([0.609862  , 0.47114058, 0.00710999])

In [32]:
b = np.random.rand(2,3)
b

array([[0.91219553, 0.4053208 , 0.51461596],
       [0.95702922, 0.76251273, 0.3476797 ]])

In [33]:
# If we want to increase the range from 0 to 10
b = np.random.rand(3)*10
b

array([9.25935078, 2.62002733, 1.40255298])

In [37]:
# arguments as low, high, size
b = np.random.randint(0,10,3)
b

array([2, 6, 5])

In [38]:
np.random.randint(2, size=10)

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1])

In [40]:
np.random.randint(5, size=(2, 4))

array([[1, 1, 2, 3],
       [1, 4, 3, 0]])

In [43]:
# numpy.empty(shape, dtype=float, order='C', *, like=None) - Return a new array of given shape and type, without initializing entries.
np.empty(4, dtype=int)

array([-1703446418,  -650991159, -1889562766,   387791407])