###### Problem-1 : NumPy 2D array
Problem Statement:  
GIven a 2D list, create a numpy 2D array using it.  
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  
Print the Numpy array.  

In [1]:
import numpy as np
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list_2d)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### Problem-2 : NumPy 0s and 1s
Problem Statement:  
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.

In [2]:
arr = np.zeros(10, dtype=int)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


###### Problem-3 : NumPy Inclusive
Problem Statement:  
Create an array with values ranging consecutively from 9 to 49 (both inclusive).  
Print the Numpy array.

In [3]:
arr = np.arange(9,50)
arr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

###### Problem-4 : Identity Matrix
Problem Statement:  
Create an integer identity matrix of size (5, 6).  
Print the Numpy array.

In [5]:
arr = np.eye(5,6, dtype=int)
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

###### Problem-5 : Cut the Rope
Problem Statement:  
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.  
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.  
Print the array element.

In [9]:
# https://towardsdatascience.com/first-step-in-data-science-with-python-numpy-5e99d6821953
arr = np.linspace(0, 5, 10)
for i in range(1, len(arr)-1):
    print(round(arr[i],2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
